# Generated by Django 5.0.5 on 2024-05-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_card', '0004_alter_glucosemeasurement_date_of_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glucosemeasurement',
            name='date_of_measurement',
            field=models.DateTimeField(),
        ),
    ]
