# Generated by Django 5.0.5 on 2024-05-09 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_doctor_about'),
        ('patient_card', '0006_glucosemeasurement_time_of_measurement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Тип активності',
                'verbose_name_plural': 'Типи активності',
            },
        ),
        migrations.AlterModelOptions(
            name='glucosemeasurement',
            options={'verbose_name': 'Замір глюкози', 'verbose_name_plural': 'Заміри глюкози'},
        ),
        migrations.CreateModel(
            name='PhysicalActivityMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_approaches', models.IntegerField(blank=True)),
                ('time_of_activity', models.CharField(blank=True, max_length=10, null=True)),
                ('commentary', models.TextField(blank=True, max_length=1000, null=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.patient')),
                ('type_of_activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patient_card.typeofactivity')),
            ],
            options={
                'verbose_name': 'Замір фізичної активності',
                'verbose_name_plural': 'Заміри фізичної активності',
            },
        ),
    ]
