# Generated by Django 5.0.5 on 2024-05-09 08:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_card', '0007_typeofactivity_alter_glucosemeasurement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalactivitymeasurement',
            name='date_of_measurement',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='physicalactivitymeasurement',
            name='time_of_activity',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
