# Generated by Django 5.0.5 on 2024-05-09 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_card', '0009_fooditem_foodmeasurement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fooditem',
            options={'verbose_name': 'Порція їжі', 'verbose_name_plural': 'Порції їжі'},
        ),
        migrations.AlterModelOptions(
            name='foodmeasurement',
            options={'verbose_name': 'Порція їжі', 'verbose_name_plural': 'Порції їжі'},
        ),
    ]
