# Generated by Django 5.0.5 on 2024-05-10 15:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_doctor_about'),
        ('patient_card', '0012_foodmeasurement_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsulineDoseMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Натщесердце', 'Натщесердце'), ('До сніданку', 'До сніданку'), ('Після сніданку', 'Після сніданку'), ('Перед перекусом', 'Перед перекусом'), ('Після перекусу', 'Після перекусу'), ('До обіду', 'До обіду'), ('Після обіду', 'Після обіду'), ('До вечері', 'До вечері'), ('Після вечері', 'Після вечері'), ('Перед сном', 'Перед сном'), ('Інше', 'Інше')])),
                ('insuline_dose', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_of_measurement', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.patient')),
            ],
            options={
                'verbose_name': 'Замір інсуліну',
                'verbose_name_plural': 'Заміри інсуліну',
            },
        ),
    ]
