# Generated by Django 5.0.5 on 2024-05-10 18:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_doctor_about'),
        ('patient_card', '0013_insulinedosemeasurement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Загальний аналіз крові', 'Загальний аналіз крові'), ('Загальний аналіз сечі', 'Загальний аналіз сечі'), ('Аналіз крові на глюкозу', 'Аналіз крові на глюкозу'), ('Аналіз крові на глікований гемоглобин', 'Аналіз крові на глікований гемоглобин'), ('Аналіз С-пептид', 'Аналіз С-пептид'), ('Комплексний аналіз "Ліпідограма" ', 'Комплексний аналіз "Ліпідограма"'), ('Інше', 'Інше')], default='Інше')),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis', models.FileField(upload_to='patients-media/analysis')),
                ('date_of_measurement', models.DateField(default=django.utils.timezone.now)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.patient')),
                ('analysis_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patient_card.analystype')),
            ],
            options={
                'verbose_name': 'Аналіз',
                'verbose_name_plural': 'Аналізи',
            },
        ),
    ]
