# Generated by Django 5.0.5 on 2024-05-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_card', '0014_analystype_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analystype',
            name='name',
            field=models.CharField(default='Інше'),
        ),
    ]
