# Generated by Django 5.0.5 on 2024-05-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_card', '0017_alter_analystype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofactivity',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
