# Generated by Django 5.0.5 on 2024-05-07 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0007_alter_doctor_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlucoseMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glucose', models.DecimalField(decimal_places=2, max_digits=4)),
                ('glucose_measurement_category', models.CharField(blank=True, choices=[('Натщесердце', 'Натщесердце'), ('До сніданку', 'До сніданку'), ('Після сніданку', 'Після сніданку'), ('Перед перекусом', 'Перед перекусом'), ('Після перекусу', 'Після перекусу'), ('До обіду', 'До обіду'), ('Після обіду', 'Після обіду'), ('До вечері', 'До вечері'), ('Після вечері', 'Після вечері'), ('Перед сном', 'Перед сном'), ('Інше', 'Інше')], null=True)),
                ('date_of_measurement', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.patient')),
            ],
        ),
    ]
