# Generated by Django 5.0.5 on 2024-05-08 07:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_card', '0005_alter_glucosemeasurement_date_of_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='glucosemeasurement',
            name='time_of_measurement',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='glucosemeasurement',
            name='date_of_measurement',
            field=models.DateField(),
        ),
    ]
