# Generated by Django 5.0.5 on 2024-05-09 19:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_doctor_about'),
        ('patient_card', '0008_physicalactivitymeasurement_date_of_measurement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Назва їжі', max_length=200)),
                ('proteins', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fats', models.DecimalField(decimal_places=2, max_digits=6)),
                ('carbohydrates', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='FoodMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insuline_dose_before', models.DecimalField(decimal_places=2, max_digits=5)),
                ('insuline_dose_after', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date_of_measurement', models.DateField(default=django.utils.timezone.now)),
                ('time_of_eating', models.TimeField(default=django.utils.timezone.now)),
                ('bread_unit', models.IntegerField()),
                ('food_items', models.ManyToManyField(to='patient_card.fooditem')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.patient')),
            ],
        ),
    ]
