# Generated by Django 5.0.5 on 2024-05-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_card', '0010_alter_fooditem_options_alter_foodmeasurement_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodmeasurement',
            options={'verbose_name': 'Замір їжі', 'verbose_name_plural': 'Заміри їжі'},
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='foodmeasurement',
            name='bread_unit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
