# Generated by Django 5.0.5 on 2024-05-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_card', '0011_alter_foodmeasurement_options_alter_fooditem_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmeasurement',
            name='category',
            field=models.CharField(choices=[('Сніданок', 'Сніданок'), ('Перекус', 'Перекус'), ('Обід', 'Обід'), ('Другий перекус', 'Другий перекус'), ('Вечеря', 'Вечеря')], default='Сніданок'),
        ),
    ]
