# Generated by Django 5.0.3 on 2024-04-26 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0007_alter_doctor_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorsProfileFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField(blank=True, max_length=1000, null=True)),
                ('date_of_created', models.DateTimeField(auto_now_add=True)),
                ('doctor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.doctor')),
                ('patient_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='login.patient')),
            ],
            options={
                'unique_together': {('doctor_id', 'patient_id')},
            },
        ),
    ]
