# Generated by Django 5.0.5 on 2024-05-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_techsupportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='techsupportticket',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='tech-support/tickets/'),
        ),
    ]
