# Generated by Django 5.0.3 on 2024-04-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_doctor_phone_number_alter_patient_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adress',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adress',
            name='house_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adress',
            name='postal_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adress',
            name='street',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='diabet_type',
            field=models.CharField(choices=[('1', '1 тип'), ('2', '2 тип'), ('null', 'Відсутній')], default='null', max_length=10),
        ),
    ]
