# Generated by Django 5.0.3 on 2024-04-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_adress_city_alter_adress_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
