# Generated by Django 5.0.5 on 2024-05-14 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_doctor_qr_code_doctor_secret_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='secret_key',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='two_factor_enabled',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='secret_key',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='two_factor_enabled',
        ),
    ]
