# Generated by Django 5.0.3 on 2024-04-10 18:13

import django.contrib.auth.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('house_number', models.IntegerField()),
                ('postal_code', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Adress',
                'verbose_name_plural': 'Adresses',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(db_index=True, max_length=255)),
                ('organization_logo', models.ImageField(blank=True, upload_to='organization-logos/')),
                ('organization_phone', models.CharField(max_length=255)),
                ('organization_email', models.EmailField(max_length=254, verbose_name='Електронна пошта')),
                ('organization_description', models.TextField()),
                ('organization_website_url', models.URLField(blank=True)),
                ('adress_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.adress')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['organization_name'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('Male', 'Чоловічий'), ('Female', 'Жіночий')], max_length=20)),
                ('age', models.IntegerField(db_index=True)),
                ('patronymic', models.CharField(blank=True, max_length=255)),
                ('avatar', models.ImageField(blank=True, default='placeholder-img.png', null=True, upload_to='profile-pics/')),
                ('work_experience', models.IntegerField(db_index=True)),
                ('specialization', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('certificate_or_diploma', models.FileField(upload_to='certificates/')),
                ('unique_connect_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('about', models.TextField()),
                ('organization_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.organization')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ['work_experience'],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('Male', 'Чоловічий'), ('Female', 'Жіночий')], max_length=20)),
                ('age', models.IntegerField(db_index=True)),
                ('patronymic', models.CharField(blank=True, max_length=255)),
                ('avatar', models.ImageField(blank=True, default='placeholder-img.png', null=True, upload_to='profile-pics/')),
                ('height', models.DecimalField(decimal_places=2, max_digits=6)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('body_mass_index', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('connect_to_doctor_date', models.DateTimeField(blank=True)),
                ('diabet_type', models.CharField(choices=[(1, '1 тип'), (2, '2 тип'), (0, 'відсутній')], db_index=True, default=0, max_length=10)),
                ('is_oninsuline', models.BooleanField(db_index=True)),
                ('adress_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.adress')),
                ('doctor_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='login.doctor')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['connect_to_doctor_date', 'diabet_type', 'is_oninsuline'],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
