# Generated by Django 5.0.3 on 2024-04-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_patient_connect_to_doctor_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='is_oninsuline',
            field=models.BooleanField(db_index=True, null=True),
        ),
    ]
