# Generated by Django 5.0.5 on 2024-05-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_doctor_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Електронна пошта'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_logo',
            field=models.ImageField(blank=True, null=True, upload_to='organization-logos/'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
